# Generated by Django 2.2.5 on 2019-09-27 20:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('isEnabled', models.BooleanField(default=True)),
                ('iexId', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('symbol_type', models.CharField(choices=[('ADR', 'ADR'), ('REIT', 'REIT'), ('Closed end fund', 'Closed end fund'), ('Secondary Issue', 'Secondary Issue'), ('Limited Partnerships', 'Limited Partnerships'), ('Common Stock', 'Common Stock'), ('ETF', 'ETF')], default='AD', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SymbolsAutocomplete',
            fields=[
                ('search', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchSymbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enter', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.Symbols')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolsAutocompleteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_symbols', to='trading.SymbolsAutocomplete')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('high_price', models.FloatField(blank=True, null=True)),
                ('low_price', models.FloatField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('uOpen', models.FloatField(blank=True, null=True)),
                ('uHigh', models.FloatField(blank=True, null=True)),
                ('uLow', models.FloatField(blank=True, null=True)),
                ('uClose', models.FloatField(blank=True, null=True)),
                ('uVolume', models.IntegerField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('changePercent', models.FloatField(blank=True, null=True)),
                ('changeOverTime', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Symbols')),
            ],
        ),
        migrations.CreateModel(
            name='AlertWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enter', models.DateField(default=datetime.date.today)),
                ('expected_min_price', models.FloatField()),
                ('expected_max_price', models.FloatField()),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('watched_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.WatchSymbols')),
            ],
        ),
    ]
