# Generated by Django 2.2 on 2019-07-31 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbols',
            old_name='isEnabled',
            new_name='isEnable',
        ),
        migrations.RemoveField(
            model_name='symbols',
            name='symbol_type',
        ),
    ]
