# Generated by Django 2.2 on 2019-07-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20190730_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symbols',
            old_name='isEnable',
            new_name='isEnabled',
        ),
    ]
