# Generated by Django 2.2 on 2019-07-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20190730_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbols',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
