# Generated by Django 2.2 on 2019-08-01 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_auto_20190730_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbols',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='symbols',
            name='symbol_type',
            field=models.CharField(choices=[('ADR', 'ADR'), ('REIT', 'REIT'), ('Closed end fund', 'Closed end fund'), ('Secondary Issue', 'Secondary Issue'), ('Limited Partnerships', 'Limited Partnerships'), ('Common Stock', 'Common Stock'), ('ETF', 'ETF')], default='AD', max_length=20),
        ),
    ]
