# Generated by Django 2.2 on 2019-08-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_auto_20190731_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
            ],
        ),
    ]
