# Generated by Django 2.2 on 2019-08-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
