# Generated by Django 2.2 on 2019-08-02 21:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_delete_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('uOpen', models.FloatField()),
                ('uHigh', models.FloatField()),
                ('uLow', models.FloatField()),
                ('uClose', models.FloatField()),
                ('uVolume', models.IntegerField()),
                ('change', models.FloatField()),
                ('changePercent', models.FloatField()),
                ('changeOverTime', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Symbols')),
            ],
        ),
    ]
