# Generated by Django 2.2 on 2019-08-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20190802_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprices',
            name='close_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
