# Generated by Django 2.2 on 2019-08-06 21:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_historicalprices_close_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enter', models.DateField(default=datetime.date.today)),
                ('current_min_price', models.FloatField()),
                ('current_max_price', models.FloatField()),
                ('expected_min_price', models.FloatField()),
                ('expected_max_price', models.FloatField()),
                ('notes', models.TextField(max_length=200)),
                ('watched_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.WatchSymbols')),
            ],
        ),
    ]
