# Generated by Django 2.2 on 2019-08-22 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alertwatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertwatch',
            name='current_max_price',
        ),
        migrations.RemoveField(
            model_name='alertwatch',
            name='current_min_price',
        ),
        migrations.AlterField(
            model_name='alertwatch',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='watchsymbols',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='watchsymbols',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Symbols', unique=True),
        ),
    ]
