# Generated by Django 2.2 on 2019-08-26 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_auto_20190822_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolsAutocomplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=20)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Symbols', unique=True)),
            ],
        ),
    ]
