# Generated by Django 2.2 on 2019-08-27 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_symbolsautocomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolsautocomplete',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Symbols'),
        ),
    ]
