# Generated by Django 2.2 on 2019-08-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_auto_20190826_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolsautocomplete',
            name='id',
        ),
        migrations.AlterField(
            model_name='symbolsautocomplete',
            name='search',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='symbolsautocomplete',
            name='symbol',
        ),
        migrations.AddField(
            model_name='symbolsautocomplete',
            name='symbol',
            field=models.ManyToManyField(to='trading.Symbols'),
        ),
    ]
