# Generated by Django 2.2 on 2019-08-27 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_auto_20190826_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolsautocomplete',
            name='symbol',
        ),
        migrations.CreateModel(
            name='SymbolsAutocompleteRelation',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.SymbolsAutocomplete')),
            ],
        ),
    ]
