# Generated by Django 2.2 on 2019-08-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_auto_20190826_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SymbolsAutocompleteRelation',
        ),
    ]
