# Generated by Django 2.2 on 2019-08-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_delete_symbolsautocompleterelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolsAutocompleteRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.SymbolsAutocomplete')),
            ],
        ),
    ]
