# Generated by Django 2.2 on 2019-08-27 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_symbolsautocompleterelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbolsautocompleterelation',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_symbols', to='trading.SymbolsAutocomplete'),
        ),
    ]
