# Generated by Django 2.2 on 2019-05-29 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_id', models.CharField(max_length=50, unique=True)),
                ('tool_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_life', models.IntegerField(default=1000)),
                ('tool_risk', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1)),
                ('date_audited', models.DateField()),
                ('audit_required', models.BooleanField()),
                ('tool_audited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooling.Tool')),
            ],
        ),
    ]
