# Generated by Django 2.2 on 2019-05-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='remaining_life',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tool',
            name='photo',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='total_life',
            field=models.IntegerField(default=0),
        ),
    ]
