# Generated by Django 2.2 on 2019-05-29 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0002_auto_20190529_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='audit_required',
        ),
        migrations.AlterField(
            model_name='condition',
            name='date_audited',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
