# Generated by Django 2.2 on 2019-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0005_auto_20190626_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='photo',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
