# Generated by Django 2.2 on 2019-06-30 14:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tooling.models


class Migration(migrations.Migration):

    dependencies = [
        ('tooling', '0008_auto_20190626_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tool',
            name='photo',
            field=models.ImageField(blank=True, upload_to=tooling.models.get_upload_path),
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=100, unique=True)),
                ('date_enter', models.DateField(default=datetime.date.today)),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tooling.Project')),
            ],
        ),
    ]
